name: docs-21-dev

on:
  pull_request:
    types:
      - closed
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'
    paths:
      - '.github/workflows/generate-docc.yml'
      - '.github/workflows/deploy-cloudflare.yml'
      - '.github/workflows/DOCS-21-DEV.yml'
      - 'Resources/docs-21-dev/**'
      - 'Sources/docs-21-dev-P256K/**'
      - 'Sources/docs-21-dev-ZKP/**'
      - 'Sources/UtilLib/**'
      - 'Sources/util/**'
      - 'Package.swift'
      - 'Package.resolved'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    name: Generate Documentation
    uses: ./.github/workflows/generate-docc.yml
    with:
      project-name: docs-21-dev
      targets: "P256K ZKP"
  
  deploy:
    name: Deploy Documentation
    needs: generate
    uses: ./.github/workflows/deploy-cloudflare.yml
    with:
      artifact-name: ${{ needs.generate.outputs.artifact-name }}
      project-name: docs-21-dev
      deploy-to-production: ${{ github.event.pull_request.merged || false }}
    secrets:
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
