name: md-21-dev

on:
  push:
    branches:
      - 'main'
    paths: &paths
      - '.github/workflows/generate-markdown.yml'
      - '.github/workflows/deploy-cloudflare.yml'
      - '.github/workflows/MD-21-DEV.yml'
      - 'Resources/md-21-dev/**'
      - 'Package.swift'
      - 'Package.resolved'

  pull_request:
    branches:
      - 'main'
    paths: *paths

  workflow_dispatch:

jobs:
  generate:
    name: Generate Markdown Documentation
    uses: ./.github/workflows/generate-markdown.yml
    with:
      project-name: md-21-dev
      ref: ${{ github.event.pull_request.head.sha || github.sha }}
      targets: "P256K ZKP"
  
  deploy:
    name: Deploy Markdown Documentation
    needs: generate
    uses: ./.github/workflows/deploy-cloudflare.yml
    with:
      artifact-name: ${{ needs.generate.outputs.artifact-name }}
      project-name: md-21-dev
      deploy-to-production: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    secrets:
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
